version: '3.4'

services:
  wsl2-bluetooth:
    image: ${DOCKER_REGISTRY-}wsl2bluetooth
    build:
      context: .
      dockerfile: WSL2-Bluetooth/Dockerfile
    volumes:
      - \\wsl.localhost\Ubuntu\run\dbus:/var/run/dbus/:z
